# A redirect rule with many of the supported properties
[[redirects]]
  from = "https://dog-academy.co/"
  to = "https://fr.dog-academy.co/"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["fr"]}


